name: Компиляция бота

on: [ push, workflow_dispatch ]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Подключение Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Настройка доступа к gradlew
        run: chmod +x ./gradlew

      - name: Сборка бота в jar
        run: ./gradlew shadowJar

      - name: Выгрузка jar
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/

      - name: Сборка бота в shadowJar
        run: ./gradlew shadowJar

      - name: Выгрузка shadowJar
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-shadowJar
          path: build/libs/
